### ISSUE TITLE
using masks and fmriprep output

### ISSUE THREAD

**Issue by amhowell2** [BIDS-Apps/fmriprep#5]
Hiya!

I'm having trouble masking the output of fmriprep so I can extract timeseries data using fslmeants. I originally thought it would be pretty easy using masks from the craddock 200 brain atlas. The problem I'm running into is the output of fmriprep is 2.9x2.9x2.9mm (which I eventually fixed by flirting the func files so they were 3x3x3 to match my atlas). However, the next issue I have is the dimension sizes are not the same (fmriprep output dimensions are: 68x80x68 and craddock atlas dimensions are 63x75x61). I was wondering if anyone had a quick way to convert the functional files to match the atlas or to put both in some sort of space so I can extract timeseries information. 

Any help would be greatly appreciated!

**Comment by chrisfilo** [comment]
I would recommend reslicing the atlas/parcellation into the dimensionality of the _preproc files instead. You can do it with this nilearn function: http://nilearn.github.io/modules/generated/nilearn.image.resample_to_img.html#nilearn.image.resample_to_img

You can also use nilearn to extract time series in one step http://nilearn.github.io/connectivity/functional_connectomes.html

PS This question seems like a better fit for http://NeuroStars.org
